# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77839c2a93e8c7a0e06b01d1c479911eeb0849970ed282180f7ca652c5b98030938f918ca9397c1c18b1b146e19f632ae38aa4d47cfe255bdaf8b70c918e120c

test:
  secret_key_base: 1aa29dd44ebd8a356133307ae97da673ad514287ec617511cbf03aeed24b566e6e4deea3617d64c2349c5cb678c62a6ba4b3c36ca3dc4b901167f594935fd7a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
